import { DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
  weight: "400",
  variable: "--bold",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  weight: "300",
  variable: "--bold",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${dmMono.variable} antialiased`}>
        <Header className={`${dmMono.variable}`} />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
